name: Java Maven Build

on:
  push:
    branches:
      - github-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: github-action

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

  create_instance:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      id: create_instance_outputs
      values: ${{ steps.set_output.outputs }}
    
    steps:
    - name: Set Output
      id: set_output
      run: echo "instance_ip=192.168.1.1" >> $GITHUB_ENV

  use_instance:
    needs: create_instance
    runs-on: ubuntu-latest

    steps:
    - name: Use Instance IP
      run: |
        echo "Instance IP: ${{ needs.create_instance_outputs.values.instance_ip }}"

  ssh_into_instance:
    needs: create_instance
    runs-on: ubuntu-latest

    steps:
    - name: Create PEM file
      run: echo -e "${{ secrets.AWS_PEM_KEY_AS_PEM }}" > cpdevopsew-us-east-2.pem

    - name: SSH into EC2 Instance and Run Commands
      run: |
        ssh -o StrictHostKeyChecking=no -i cpdevopsew-us-east-2.pem ubuntu@${{ needs.create_instance.outputs.instance_ip }} << 'EOF'
        sudo apt update -y
        sudo apt install -y git
        git clone https://github.com/chandradeoarya/devops-cicd-gaction-java-spring.git
        sudo apt install -y maven
        cd devops-cicd-gaction-java-spring/
        mvn clean install
        mvn spring-boot:run
        EOF
